from collections import deque
from debugger import DebugPrinter

# should probably really write this in C... would be less work..
# so this is supposed to read symbolic code generated by the compiler
# and execute the generated intermediate code via stack machine.

class VirtualRunTime:
    def __init__(self):
        self.instructions = []
        self.v_stack = []
        self.v_data_seg = []
        self.debugger = DebugPrinter()

    def push(self, arg):
        pass

    def pop(self, arg):
        pass

    def op_add(self):
        pass

    def op_sub(self):
        pass
    
    def op_mult(self):
        pass

    def load_instructions(self, instructions):
        """loads set of instructions"""
        self.instructions = instructions

    def load_symbol_table(self, symbol_table):
        self.symbol_table = symbol_table
        self.symbol_table.print_table()

    def print_instructions(self):
        print self.instructions


